name: Update Portfolio Data

on:
  schedule:
    # Run hourly during market hours (UTC)
    # 9 AM - 4 PM ET converted to UTC (13:00 - 20:00)
    - cron: '0 13-20 * * 1-5'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Update portfolio data
        env:
          # Database connection
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          
          # Redis connection
          REDIS_URL: ${{ secrets.REDIS_URL }}
          
          # Other environment variables your app needs
          VERCEL_URL: ${{ secrets.VERCEL_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: node scripts/update-portfolio.js 